server.port: 8082

spring:
    application.name: temperature-processing
    rabbitmq:
      host: rabbitmq
      port: 5672
      username: ${RABBITMQ_DEFAULT_USER}
      password: ${RABBITMQ_DEFAULT_PASS}